"""Fix nullability constraints

Revision ID: b8748550b5fa
Revises: 912c36fa4517
Create Date: 2025-04-10 18:24:32.213349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8748550b5fa'
down_revision: Union[str, None] = '912c36fa4517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subjects', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subjects', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
